# Generated by Django 5.0 on 2026-03-10 00:00
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("available_slots", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
    ]
